### ISSUE TITLE
Incompatible with wget from BusyBox (alpine linux)

### ISSUE THREAD

**Issue by alexandrexaviersm** [kafka4beam/lz4b#5]
Trying to use this against an Alpine Linux server, but I'm getting the following error:

```
#19 71.58 ===> Compiling rebar3_hex
#19 72.22 _build/default/plugins/rebar3_hex/src/rebar3_hex_organization.erl:391:5: Warning: public_key:ssh_encode/2 is deprecated and will be removed in OTP 26; use ssh_file:encode/2 instead
#19 72.22 
#19 72.30 make: Entering directory '/app/deps/lz4b/c_src'
#19 72.31 wget -N https://github.com/lz4/lz4/archive/v1.9.2.tar.gz
#19 72.31 wget: unrecognized option: N
#19 72.31 BusyBox v1.34.1 (2021-11-23 00:57:35 UTC) multi-call binary.
#19 72.31 
#19 72.31 Usage: wget [-cqS] [--spider] [-O FILE] [-o LOGFILE] [--header 'HEADER: VALUE'] [-Y on/off]
#19 72.31 	[-P DIR] [-U AGENT] [-T SEC] URL...
#19 72.31 
#19 72.31 Retrieve files via HTTP or FTP
#19 72.31 
#19 72.31 	--spider	Only check URL existence: $? is 0 if exists
#19 72.31 	-c		Continue retrieval of aborted transfer
#19 72.31 	-q		Quiet
#19 72.31 	-P DIR		Save to DIR (default .)
#19 72.31 	-S    		Show server response
#19 72.31 	-T SEC		Network read timeout is SEC seconds
#19 72.31 	-O FILE		Save to FILE ('-' for stdout)
#19 72.31 	-o LOGFILE	Log messages to FILE
#19 72.31 	-U STR		Use STR for User-Agent header
#19 72.31 	-Y on/off	Use proxy
#19 72.31 make: *** [Makefile:69: lz4-1.9.2] Error 1
#19 72.31 make: Leaving directory '/app/deps/lz4b/c_src'
#19 72.31 ===> Hook for compile failed!
#19 72.31 
#19 72.33 ==> events
#19 72.33 ** (Mix) Could not compile dependency :lz4b, "/root/.mix/rebar3 bare compile --paths /app/_build/prod/lib/*/ebin" command failed. You can recompile this dependency with "mix deps.compile lz4b", update it with "mix deps.update lz4b" or clean it with "mix deps.clean lz4b"
------
executor failed running [/bin/sh -c mix do deps.clean --all, deps.get, compile]: exit code: 1

Exited with code exit status 1
CircleCI received exit code 1
```

It looks like Alpine Linux uses a different wget version, is it possible to use another alternative instead of `wget -N` in the Makefile?

Thanks

**Comment by alexandrexaviersm** [comment]
Hi @zmstone - I did some tests with the docker image `hexpm/elixir:1.12.3-erlang-24.2-alpine-3.15.0` using both lz4b versions
`{:lz4b, "~> 0.0.8"}` 
and
`{:lz4b, git: "https://github.com/kafka4beam/lz4b.git", branch: "fix-wgeet-compatibility"}` 

I find out that for `lz4b branch: "fix-wgeet-compatibility"` I have to install `curl` on the alpine server and to make  `lz4b v0.0.8` to work I have to install `wget` on the alpine server (installing wget makes the server use GNU Wget instead of BusyBox Wget).

So the solution for this issue can be resolved by just installing wget on the alpine server.
```
{:lz4b, "~> 0.0.8"} 
apk add --update --no-cache make git wget build-base
```

Or if we want to go with the branch: "fix-wgeet-compatibility", curl has to be installed.
```
{:lz4b, git: "https://github.com/kafka4beam/lz4b.git", branch: "fix-wgeet-compatibility"} 
apk add --update --no-cache make git curl build-base
```

**Comment by alexandrexaviersm** [comment]
So if you guys want to continue with the current version, we can close this issue. But you guys want to go ahead with the new branch, it also seems to be working fine.

**Comment by zmstone** [comment]
thank you @alexandrexaviersm for testing it out.
my experience has been: wget gives more surprises than curl.
what's your preferences?
@alexandrexaviersm  @qzhuyan @ieQu1 ?
