### ISSUE TITLE
Mac M1 (arm64) Support

### ISSUE THREAD

**Issue by tpitale** [kafka4beam/lz4b#7]
This https://github.com/kafka4beam/lz4b/blob/dde08abe4fae6a73b0678454e2dded04f49e5a83/c_src/Makefile#L25-L30 hardcodes x86_64 for Darwin systems. Apple now sells their computers with an ARM chip.

I'll try to submit a PR.

**Comment by tpitale** [comment]
Or is this the official repo? https://gitlab.com/tpitale/lz4b

**Comment by zmstone** [comment]
Hi @tpitale 
Do you mean the upstream of your fork https://gitlab.com/qzhuyan/lz4b ?
I believe this one should become more 'official' than @qzhuyan's private fork although Zhuwei (William) is so far still the sole maintainer of this repo.

**Comment by tpitale** [comment]
Yeah, wrong link. It seems like GH is the repo with the latest. Gitlab is just shown on hex.pm.

**Comment by tpitale** [comment]
I have a fix that's working locally. I'll submit a PR (Monday, maybe sooner).
